### ISSUE TITLE
setPanelOptions is not a function

### ISSUE THREAD

**Issue by versatildefuy** [grafana/grafana-starter-panel#18]
Hello guys,

I tried to install this plugin in Grafana 6.5.3 (built from sources, Linux environment) and after I have executed `yarn install` and `yarn dev` this error message is shown in browser console:

```
Error loading panel plugin: myorgid-simple-panel Error: "(new _grafana_data__WEBPACK_IMPORTED_MODULE_0__.PanelPlugin(...)).setPanelOptions is not a function
  Evaluating http://localhost:3000/public/plugins/myorgid-simple-panel/module.js
  Loading plugins/myorgid-simple-panel/module"
    ts module.ts:5
    Webpack 9
        __webpack_require__
        <anonymous>
        <anonymous>
        i
        qe
        j
        O
        k
        ./node_modules/systemjs/dist/system.js/</</f.prototype[i.resolveInstantiate]/</<
plugin_loader.ts:246
```

I don't know what to do because I did nothing :) but installing it.

Have I forgotten something?

Thank you in advance

**Comment by federico-d** [comment]
same here

Node.js v12.16.3
grafana 6.7.3

`plugin_loader.ts:267 Error loading panel plugin: myorgid-simple-panel TypeError: (intermediate value).setPanelOptions is not a function
    at Module../module.ts (:3000/public/plugins/myorgid-simple-panel/module.js:411)
    at __webpack_require__ (:3000/public/plugins/myorgid-simple-panel/module.js:20)
    at eval (:3000/public/plugins/myorgid-simple-panel/module.js:84)
    at eval (:3000/public/plugins/myorgid-simple-panel/module.js:87)
    at o (system.js:4)
    at system.js:4
    at system.js:4
    at O (system.js:4)
    at S (system.js:4)
    at system.js:4`

**Comment by briangann** [comment]
that is a v7 option that was updated too soon

**Comment by Gowee** [comment]
That is a new function introduced by Grafana 7.x which is not released yet.

To make the template work for my Grafana 6.x, I check out the commit just before the one on April 26, then everything goes well.

**Comment by proactivefly** [comment]
same problem

**Comment by ryanrishi** [comment]
You can run Grafana v7 (in beta) with Docker:
```sh
docker run -d -p 3000:3000 -v "$(pwd)"/grafana-plugins:/var/lib/grafana/plugins --name=grafana grafana/grafana:7.0.0-beta3
```

This is adapted from the [Grafana "Build a Panel Plugin" tutorial](https://grafana.com/tutorials/build-a-panel-plugin/#2).

**Comment by SilkeDH** [comment]
Same here. Aren't there any tutorials about building a panel plugin for versions < 7.0 ?

**Comment by ivanprostran** [comment]
I've managed to create a plugin for versions < 6.x.x

1. You can download the version that supports 6.x.x, that is https://github.com/grafana/simple-react-panel/tree/20200211_fake_release/src

2. You can adjust the grafana-toolkit to use the old template:

file: grafana-6.7.4\packages\grafana-toolkit\src\cli\tasks\plugin\create.ts

>> await simpleGit.clone(url, dest, ['--branch', '20200211_fake_release']);

```
export const fetchTemplate = useSpinner<{ type: PluginType; dest: string }>(
  'Fetching plugin template...',
  async ({ type, dest }) => {
    const url = RepositoriesPaths[type];
    if (!url) {
      throw new Error('Unknown plugin type');
    }

    //await simpleGit.clone(url, dest);
    await simpleGit.clone(url, dest, ['--branch', '20200211_fake_release']);
  }
);
```

Normally you can use the create plugin the same way as with npx:

`node bin/grafana-toolkit.js plugin:create my-react-plugin`

**Comment by gpmaestri** [comment]
I cloned the branch but it wont build, verbose build bellow:

`npm run-script build --verbose
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'run-script',
npm verb cli   'build',
npm verb cli   '--verbose'
npm verb cli ]
npm info using npm@6.14.6
npm info using node@v12.18.4
npm verb run-script [ 'prebuild', 'build', 'postbuild' ]
npm info lifecycle simple-react-panel@1.0.0~prebuild: simple-react-panel@1.0.0
npm info lifecycle simple-react-panel@1.0.0~build: simple-react-panel@1.0.0

> simple-react-panel@1.0.0 build C:\Users\gpmae\Documents\localhost\grafana-starter-panel-version-6
> grafana-toolkit plugin:build

✔ Preparing
✔ Linting
ts-jest[versions] (WARN) Version 25.5.4 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=26.0.0 <27.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.
 PASS  src/module.test.ts

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.586s
Ran all test suites with tests matching "".
✔ Running tests
\ Compiling...  Starting type checking service...
  Using 1 worker with 2048MB memory limit
\ Compiling...  ERROR in C:/Users/gpmae/Documents/localhost/grafana-starter-panel-version-6/src/SimpleEditor.tsx(2,10):
  TS2305: Module '"../node_modules/@grafana/ui"' has no exported member 'FormField'.

   Hash: 16c36b78ddc24c656e03
  Version: webpack 4.41.5
  Time: 11916ms
  Built at: 2020-12-12 16:40:56
          Asset       Size  Chunks                   Chunk Names
   CHANGELOG.md  111 bytes          [emitted]
        LICENSE   11.1 KiB          [emitted]
      README.md   1.22 KiB          [emitted]
   img/logo.svg  870 bytes          [emitted]
      module.js   3.03 KiB       0  [emitted]        module
  module.js.map   19.9 KiB       0  [emitted] [dev]  module
    plugin.json  657 bytes          [emitted]
  Entrypoint module = module.js module.js.map
  [0] external "react" 42 bytes {0} [built]
  [1] external "@grafana/data" 42 bytes {0} [built]
  [2] external "@grafana/ui" 42 bytes {0} [built]
  [3] ./module.ts + 4 modules 12.8 KiB {0} [built]
      | ./module.ts 268 bytes [built]
      | ./types.ts 54 bytes [built]
      | ./SimplePanel.tsx 1.37 KiB [built]
      | ./SimpleEditor.tsx 1.04 KiB [built]
      | ../node_modules/tslib/tslib.es6.js 10 KiB [built]

  ERROR in C:/Users/gpmae/Documents/localhost/grafana-starter-panel-version-6/src/SimpleEditor.tsx
  ERROR in C:/Users/gpmae/Documents/localhost/grafana-starter-panel-version-6/src/SimpleEditor.tsx(2,10):
  TS2305: Module '"../node_modules/@grafana/ui"' has no exported member 'FormField'.

  Trace: Build failed
      at C:\Users\gpmae\Documents\localhost\grafana-starter-panel-version-6\node_modules\@grafana\src\cli\utils\useSpinner.ts:10:13
      at step (C:\Users\gpmae\Documents\localhost\grafana-starter-panel-version-6\node_modules\@grafana\toolkit\node_modules\tslib\tslib.js:140:27)
      at Object.throw (C:\Users\gpmae\Documents\localhost\grafana-starter-panel-version-6\node_modules\@grafana\toolkit\node_modules\tslib\tslib.js:121:57)
      at rejected (C:\Users\gpmae\Documents\localhost\grafana-starter-panel-version-6\node_modules\@grafana\toolkit\node_modules\tslib\tslib.js:112:69)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
✖ Build failed
npm verb lifecycle simple-react-panel@1.0.0~build: unsafe-perm in lifecycle true
npm verb lifecycle simple-react-panel@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\gpmae\Documents\localhost\grafana-starter-panel-version-6\node_modules\.bin;C:\Users\gpmae\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\gpmae\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\nodejs;C:\Users\gpmae\AppData\Local\Microsoft\WindowsApps;C:\Users\gpmae\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\gpmae\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
npm verb lifecycle simple-react-panel@1.0.0~build: CWD: C:\Users\gpmae\Documents\localhost\grafana-starter-panel-version-6
npm info lifecycle simple-react-panel@1.0.0~build: Failed to exec build script
npm verb stack Error: simple-react-panel@1.0.0 build: `grafana-toolkit plugin:build`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
npm verb stack     at EventEmitter.emit (events.js:315:20)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:315:20)
npm verb stack     at maybeClose (internal/child_process.js:1021:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
npm verb pkgid simple-react-panel@1.0.0
npm verb cwd C:\Users\gpmae\Documents\localhost\grafana-starter-panel-version-6
npm verb Windows_NT 10.0.19041
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "build" "--verbose"
npm verb node v12.18.4
npm verb npm  v6.14.6
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! simple-react-panel@1.0.0 build: `grafana-toolkit plugin:build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the simple-react-panel@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 24004ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gpmae\AppData\Roaming\npm-cache\_logs\2020-12-12T19_40_56_833Z-debug.log`
