### ISSUE TITLE
Add the actual needed dependencies in case yarn is not used

### ISSUE THREAD

**Issue by passcod** [grafana/grafana-starter-panel#19]
The yarn thing is just a guess, because I ripped it out immediately. But doing so, I discovered I then had to install a bunch of packages that were just? never specified?

```
"@babel/preset-env": "^7.10.4",              
"@grafana/tsconfig": "^1.0.0-rc1",           
"babel-loader": "^8.1.0",                    
"babel-plugin-angularjs-annotate": "^0.10.0",
"ts-loader": "^8.0.1",                       
"tslib": "^2.0.0"                            
```

Without that it just doesn't build.

That was a frustrating experience! Hope this helps someone else

**Comment by marcusolsson** [comment]
Closing this as I believe this shouldn't be needed anymore.
