### ISSUE TITLE
ENV variables are not available in plugin

### ISSUE THREAD

**Issue by lucassardois** [grafana/grafana-starter-panel#26]
I'm trying to pass environment variables to the plugin to be able to configure it.
I have the env variable `REACT_APP_API_URL` set, I can see it in my container by running the `env` command.
But for some reasons `console.log(process.env)` is empty when the plugin is executed on the Grafana dashboard.

**Comment by marcusolsson** [comment]
If this was possible, it would be a security risk. Each plugin receives a filtered set of environment variables that are safe to use.
